info:
  contact: {}
paths:
  /v1/control/manual:
    get:
      consumes:
      - application/json
      description: Receive manual control commands via WebSocket
      parameters:
      - description: Wheel Speeds
        in: body
        name: speeds
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
      summary: Control the vehicle manually
      tags:
      - control
swagger: "2.0"
