services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: race

  adminer:
    image: adminer
    restart: always
    ports:
      - 1333:8080
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  psql-data:
