name: CI Mobile

on:
  pull_request:
    paths:
      - "apps/mobile/**"
    types:
      - opened
      - reopened
  push:
    paths:
      - "apps/mobile/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm --filter mobile install --no-frozen-lockfile

      - name: Lint
        run: pnpm --filter mobile lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        shell: bash
        working-directory: apps/mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm@9.4.0

      - name: Install dependencies
        run: pnpm --filter mobile install --no-frozen-lockfile

      - name: TypeScript
        run: pnpm --filter mobile type

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: typescript
    defaults:
      run:
        shell: bash
        working-directory: apps/mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm --filter mobile install --no-frozen-lockfile

      - name: Test
        run: pnpm --filter mobile test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: typescript
    defaults:
      run:
        shell: bash
        working-directory: apps/mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm --filter mobile install --no-frozen-lockfile

      - name: Build
        run: pnpm --filter mobile build
