name: Web Frontend CI

on:
  pull_request:
    paths:
      - "apps/web/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
